### ISSUE TITLE
Element inversion Problem

### ISSUE THREAD

**Issue by shon1019** [liminchen/OptCuts#13]
When I run a big object  , I got "Element inversion detected" sometimes . How can I solve this problem ?

This is my object
https://drive.google.com/file/d/185agVSrRBjs2T3lbl1UVxIxSbucVBe22/view?usp=sharing

This is my batch input
' 100 ' + meshFolderPath + inputModelNameI + ' 0.999 1 0 4.1 1 0'

**Comment by liminchen** [comment]
Yeah, it's a general problem of Tuttes initialization for large and curvy objects -- the rounding error makes elements numerically inverted.
There might be 2 ways to tackle this:
1. see whether https://github.com/hankstag/progressive_embedding can provide an inversion-free parameterization for your model and use this parameterization as initial map for OptCuts;
2. if it does not hurt, try simplify your model.
Thanks!
