### ISSUE TITLE
Cmake error about TBB

### ISSUE THREAD

**Issue by lidh15** [liminchen/OptCuts#15]
CMake Error at CMakeLists.txt:33 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by liminchen** [comment]
If you do git clone --recursive, TBB should be downloaded with the repository. Have you tried that? I haven't encountered this issue before.

**Comment by lidh15** [comment]
![image](https://user-images.githubusercontent.com/14806954/74200397-c3924000-4c5e-11ea-96c0-48341aa1d53c.png)
I don't know why but this is the cmake repo of downloaded TBB, no TBBConfig.cmake or tbb-config.cmake in it.

**Comment by lidh15** [comment]
I also tried to download the latest TBB into the folder manually, though solving the problem in cmake,  it brings some compile errors in igl_stb_image.

**Comment by liminchen** [comment]
On my Mac I just tried that after you encounter this error (TBB has already been downloaded), then comment out line 31 and 32 in CMakeList.txt and recompile with
`python build.py`
works.
It's probably because TBB has some update with errors. Let me see how to fix it.

**Comment by lidh15** [comment]
Sorry but that changed nothing on my computer, still the same error.
By the way, I'm using Win10 and CMake version 3.16.0-rc3 and compiler MSVC 19.24.28316.0 if the environment matter.

**Comment by liminchen** [comment]
Yeah I haven't tested it on Windows. It would be great if you can run it on a Mac or Ubuntu machine.

**Comment by lidh15** [comment]
I did test it on a Ubuntu server (original code, did not comment out line 31 and 32) of my organization, complied successfully and the demo output was following:

~/OptCuts$ python batch.py
igl::opengl::glfw::Viewer usage:
  [drag]  Rotate scene
  A,a     Toggle animation (tight draw loop)
  F,f     Toggle face based
  I,i     Toggle invert normals
  L,l     Toggle wireframe
  O,o     Toggle orthographic/perspective projection
  T,t     Toggle filled faces
  Z       Snap to canonical view
  [,]     Toggle between rotation control types (trackball, two-axis
          valuator with fixed up, 2D mode with no rotation))
  <,>     Toggle between models
  ;       Toggle vertex labels
  :       Toggle face labels
Offline optimization mode
use b_d = 4.1
bijectivity ON
random 2-edge initial cut for closed surface
E_initial = 3.73973
Requested OpenGL version 3.3, got version 1.4The GLFW library is not initializedThe GLFW library is not initializedThe GLFW library is not initializedFloating point exception (core dumped)

And the display.html generated is empty. I think it's because of the OpenGL version but it's not my own machine so I cannot install or update OpenGL.

**Comment by liminchen** [comment]
On Ubuntu without OpenGL you can try to run OptCuts with mode 100 by modifying line 12 of batch.py to
`runCommand = FracCutsPath + ' 100 ' + meshFolderPath + inputModelNameI + ' 0.999 1 0 4.1 1 0'`

**Comment by liminchen** [comment]
So I just fixed the TBB error by switching to automatically download it from a stable source.

**Comment by lidh15** [comment]
After the update it performs exactly the same as manually download the latest TBB.
> I also tried to download the latest TBB into the folder manually, though solving the problem in cmake, it brings some compile errors in igl_stb_image.
The first several lines of the error is as follows:

I:\GitHub\OptCuts\ext\libigl\external\stb_image\igl_stb_image.h(7,3): error C3861: “visibility”: 找不到标识符 [I:\GitHub\OptCuts\build\stb_image\igl_stb_image.vcxproj]
I:\GitHub\OptCuts\ext\libigl\external\stb_image\igl_stb_image.h(7,3): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [I:\GitHub\OptCuts\build\stb_image\igl_stb_image.vcxproj]
I:\GitHub\OptCuts\ext\libigl\external\stb_image\igl_stb_image.h(7,38): error C2448: “igl::__attribute__”: 函数样式初始值设定项类似函数定义 [I:\GitHub\OptCuts\build\stb_image\igl_stb_image.vcxproj]
I:\GitHub\OptCuts\ext\libigl\external\stb_image\igl_stb_image.h(8,3): error C3861: “visibility”: 找不到标识符 [I:\GitHub\OptCuts\build\stb_image\igl_stb_image.vcxproj]
I:\GitHub\OptCuts\ext\libigl\external\stb_image\igl_stb_image.h(8,3): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [I:\GitHub\OptCuts\build\stb_image\igl_stb_image.vcxproj]
I:\GitHub\OptCuts\ext\libigl\external\stb_image\igl_stb_image.h(8,3): error C2374: “igl::__attribute__”: 重定义；多次 初始化 [I:\GitHub\OptCuts\build\stb_image\igl_stb_image.vcxproj]
I:\GitHub\OptCuts\ext\libigl\external\stb_image\igl_stb_image.h(7): message : 见“igl::__attribute__”的声明 [I:\GitHub\OptCuts\build\stb_image\igl_stb_image.vcxproj]

And there are several hundred more lines.

And when I try  this on the server:
> On Ubuntu without OpenGL you can try to run OptCuts with mode 100 by modifying line 12 of batch.py to
> `runCommand = FracCutsPath + ' 100 ' + meshFolderPath + inputModelNameI + ' 0.999 1 0 4.1 1 0'`
The HTML is not empty, but still, no desired png files were generated at all:
![image](https://user-images.githubusercontent.com/14806954/74206048-afa40980-4c71-11ea-8803-3e90eb955d8c.png)

**Comment by liminchen** [comment]
Yes these are expected. Windows is still not guarantee to work automatically, and without OpenGL there's not images generated, but others like statistics will be fine to show there.
