### ISSUE TITLE
please clean up the mesh and retry.

### ISSUE THREAD

**Issue by surheaven** [liminchen/OptCuts#18]
when i run ' python batch.py', there is a bug:
['tmp.obj']
igl::opengl::glfw::Viewer usage:
  [drag]  Rotate scene
  A,a     Toggle animation (tight draw loop)
  F,f     Toggle face based
  I,i     Toggle invert normals
  L,l     Toggle wireframe
  O,o     Toggle orthographic/perspective projection
  T,t     Toggle filled faces
  Z       Snap to canonical view
  [,]     Toggle between rotation control types (trackball, two-axis
          valuator with fixed up, 2D mode with no rotation))
  <,>     Toggle between models
  ;       Toggle vertex labels
  :       Toggle face labels
Offline optimization mode
use b_d = 4.1
bijectivity ON
random 2-edge initial cut for closed surface
No UV provided, initialized to all 0
area of triangle No.18564 (0-index) is 0
vertex indices (0-index) are 9987 9970 9494
area of triangle No.29282 (0-index) is 0
vertex indices (0-index) are 15573 15574 15575
area of triangle No.43411 (0-index) is 0
vertex indices (0-index) are 21559 21561 21580
area of triangle No.46797 (0-index) is 0
vertex indices (0-index) are 23202 24043 24101
area of triangle No.51016 (0-index) is 0
vertex indices (0-index) are 26011 25138 26114
area of triangle No.75614 (0-index) is 0
vertex indices (0-index) are 38329 37490 38330
area of triangle No.101009 (0-index) is 0
vertex indices (0-index) are 50434 50424 50217
area of triangle No.112803 (0-index) is 0
vertex indices (0-index) are 56312 56893 56124
area of triangle No.113286 (0-index) is 0
vertex indices (0-index) are 56324 57234 56304
area of triangle No.116316 (0-index) is 0
vertex indices (0-index) are 58626 58625 58582
area of triangle No.118220 (0-index) is 0
vertex indices (0-index) are 59808 58427 58424
area of triangle No.118931 (0-index) is 0
vertex indices (0-index) are 58522 58524 58371
area of triangle No.128351 (0-index) is 0
vertex indices (0-index) are 64314 64117 64128
please clean up the mesh and retry.

can you tell me how to solve? thanks!

**Comment by liminchen** [comment]
It looks like there are triangles with 0 area in the mesh. You should probably merge these triangles into a single vertex, e.g., merging vertex 64314 64117 64128 into a single vertex as suggested by
```
area of triangle No.128351 (0-index) is 0
vertex indices (0-index) are 64314 64117 64128
```
This should resolve the issue. Since OptCuts generates maps without any triangle flip, it does not allow 0-area degenerated triangles in the input at the first place.

**Comment by surheaven** [comment]
thanks
