### ISSUE TITLE
Will OptCuts add new cuts to a mesh that already has boundaries?

### ISSUE THREAD

**Issue by alecjacobson** [liminchen/OptCuts#19]
This t-shirt has boundaries and seems to be crashing optcuts
[simple-shirt-1000.obj.zip](https://github.com/liminchen/OptCuts/files/14482944/simple-shirt-1000.obj.zip)

**Comment by liminchen** [comment]
The issue is that OptCuts didn't handle input surfaces with multiple disconnected components if no UV was given. I just fixed it in 1904d017b1e229c553e8b7ec719ab79334103b3a, right now it works, including your input, as long as all the components are in disk topology.

**Comment by liminchen** [comment]
Made a more reliable fix in 2218d87dff5a97d795c715ca6234795486692fdd

**Comment by alecjacobson** [comment]
Awesome! thanks so much
