### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by Veloctor** [liminchen/OptCuts#20]
error when run "python build.py": '"mkdir build' 不是内部或外部命令，也不是可运行的程序

**Comment by Veloctor** [comment]
another error while run build.py commands maunally: "make : 无法将“make”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。"

**Comment by Veloctor** [comment]
building the cmake generated vs2019 sln manually: 
![image](https://github.com/liminchen/OptCuts/assets/55224044/78b578fd-eec9-461f-ad85-42e0a12662b6)

**Comment by liminchen** [comment]
你好，OptCuts目前只支持MacOS和Linux

**Comment by Veloctor** [comment]
你好，有支持Windows的计划吗？这边想集成进工业软件

**Comment by liminchen** [comment]
暂时没有。你们有兴趣可以看看https://geometrycollective.github.io/boundary-first-flattening/

**Comment by Veloctor** [comment]
好的。方便的话还请注明一下不支持Windows，之前尝试编译浪费了很多时间，最终放弃了，用了XAtlas

**Comment by liminchen** [comment]
嗯，注明的有：
Tips for Windows users: Running OptCuts on Windows is possible to encounter severe speed issues, which can be related to the memory management of Eigen backend. A useful suggestion is to swap out Eigen's malloc with dlmalloc.
另外只是不支持像在mac和Linux上一键编译，把库配好是没问题的。
