### ISSUE TITLE
UV scale problem 

### ISSUE THREAD

**Issue by shon1019** [liminchen/OptCuts#9]
Why my output obj's UV is not  in range 0~1

**Comment by liminchen** [comment]
Thanks for the question! For research purposes we output the UV with the original scale. I can add an option or an extra output file with the UV scaled to 0~1.

**Comment by liminchen** [comment]
solved with https://github.com/liminchen/OptCuts/commit/c97acc49937f8e7da7ca8305b6d40262251c33bc
